[[files]]
name = "rustc/gcc/gmp-6.3.0.tar.bz2"
source = "https://gmplib.org/download/gmp/gmp-6.3.0.tar.bz2"
sha256 = "ac28211a7cfb609bae2e2c8d6058d66c8fe96434f740cf6fe2e47b000d1c20cb"
license = "GNU General Public License"

[[files]]
name = "rustc/gcc/mpfr-4.2.2.tar.bz2"
source = "https://www.mpfr.org/mpfr-current/mpfr-4.2.2.tar.bz2"
sha256 = "9ad62c7dc910303cd384ff8f1f4767a655124980bb6d8650fe62c815a231bb7b"
license = "GNU General Public License"

[[files]]
name = "rustc/gcc/mpc-1.3.1.tar.gz"
source = "https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz"
sha256 = "ab642492f5cf882b74aa0cb730cd410a81edcdbec895183ce930e706c1c759b8"
license = "GNU General Public License"

[[files]]
name = "rustc/gcc/gcc-9.2.0.tar.xz"
sha256 = "ea6ef08f121239da5695f76c9b33637a118dcf63e24164422231917fa61fb206"
source = "https://ftp.gnu.org/gnu/gcc/gcc-9.2.0/gcc-9.2.0.tar.xz"
license = "GNU General Public License"

[[files]]
name = "rustc/gcc/gcc-9.5.0.tar.xz"
sha256 = "27769f64ef1d4cd5e2be8682c0c93f9887983e6cfd1a927ce5a0a2915a95cf8f"
source = "https://ftp.gnu.org/gnu/gcc/gcc-9.5.0/gcc-9.5.0.tar.xz"
license = "GNU General Public License"
