[[files]]
name = "rustc/gcc/gmp-6.3.0.tar.bz2"
source = "https://gmplib.org/download/gmp/gmp-6.3.0.tar.bz2"
sha256 = "ac28211a7cfb609bae2e2c8d6058d66c8fe96434f740cf6fe2e47b000d1c20cb"
license = "GNU General Public License"
