[[files]]
name = "rustc/llvm-mingw-20251104-ucrt-aarch64.zip"
sha256 = "a71358c7302cfa55a7ec1b86c75ab3672d11c21399fc5d5fa039c0b335b090db"
source = "https://github.com/mstorsjo/llvm-mingw/releases/download/20251104/llvm-mingw-20251104-ucrt-aarch64.zip"
license = "Apache License v2.0 with LLVM Exceptions"

[[files]]
name = "rustc/llvm-mingw-20251104-ucrt-x86_64.zip"
sha256 = "171b298f46fa4b5653dc7b01cc5e709caca645991be8e1b0724466c4a282a1ac"
source = "https://github.com/mstorsjo/llvm-mingw/releases/download/20251104/llvm-mingw-20251104-ucrt-x86_64.zip"
license = "Apache License v2.0 with LLVM Exceptions"
