[[files]]
name = "libc/2016-11-06/freebsd.qcow2.gz"
sha256 = "0c69e10b8bfeb829e560150559de1966ff796cf31c4757cef91653da28b7cbf3"
legacy = true

[[files]]
name = "libc/2016-11-06/openbsd-6.0-without-pkgs.qcow2"
sha256 = "525595ce32176a3e43722efb26336169ea48a0d488a1fa5ad133b41c9c8f51de"
legacy = true

[[files]]
name = "libc/2018-03-15/FreeBSD-11.1-RELEASE-amd64.qcow2.xz"
sha256 = "5d1e7b4ecbf490d2d4798a1b86b847761667c1a1014c8309a1871c175a495bd1"
legacy = true

[[files]]
name = "libc/OpenWrt-SDK-ar71xx-generic_gcc-5.3.0_musl-1.1.15.Linux-x86_64.tar.bz2"
sha256 = "e31adea0bad3a36f56c87309dde8e7e1205b71b1be908eca00504bc15198ce62"
legacy = true

[[files]]
name = "libc/OpenWrt-Toolchain-malta-le_gcc-5.3.0_musl-1.1.15.Linux-x86_64.tar.bz2"
sha256 = "ad41df333c059e552171b9ece2efbc177e9da389062a564b1883b6f60ca329fd"
legacy = true
skip-validation = true # duplicate hash

[[files]]
name = "libc/musl-1.1.24.tar.gz"
sha256 = "1370c9a812b2cf2a7d92802510cca0058cc37e66a7bedd70051f0a34015022a3"
source = "https://www.musl-libc.org/releases/musl-1.1.24.tar.gz"
license = "MIT"

[[files]]
name = "libc/musl-1.2.3.tar.gz"
sha256 = "7d5b0b6062521e4627e099e4c9dc8248d32a30285e959b7eecaa780cf8cfd4a4"
source = "https://www.musl-libc.org/releases/musl-1.2.3.tar.gz"
license = "MIT"

[[files]]
name = "libc/musl-1.2.5.tar.gz"
sha256 = "a9a118bbe84d8764da0ea0d28b3ab3fae8477fc7e4085d90102b8596fc7c75e4"
source = "https://www.musl-libc.org/releases/musl-1.2.5.tar.gz"
license = "MIT"
